name: Deploy docs

on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Commit and push docs
        run: |
          if [ -z "$(git status --porcelain docs)" ]; then
            echo "No changes in docs. Skipping commit."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "chore(ci): update docs [skip ci]"
          git push